### ISSUE TITLE
Can we have a interaction between EHR UI and service provider

### ISSUE THREAD

**Issue by jitendrasahu007** [cds-hooks/sandbox#66]
Hi,
I would like to understand is there any way to communicate between card UI and service builder.

Ask 1: Let's say : In sandbox  medication-prescribe hook example (http://sandbox.cds-hooks.org/), If they click 'change to generic' button, I want some information (some custom information used in the card) to share it to service provider.
Is there any possibility to create any button click event (Change to Generic) or any custom hook that can be called through this event.

Ask 2: I want to keep a feedback text-box inside the Card UI, and send the info to service.

Please share any link if you have any example for this.

**Comment by kpshek** [comment]
Hi @jitendrasahu007 - what you are asking for is outside of the CDS Hooks specification. The Sandbox project here only implements the specification and will never implement things outside of the spec (since we want it to serve as a reference implementation).

You are more than welcome to fork the Sandbox here and modify it to your liking and/or suggest changes to the CDS Hooks specification at https://github.com/cds-hooks/docs/issues. Additionally, as we discussed earlier on #63, you are free to use extensions for the functionality you are asking about.

I'm closing this as there isn't any changes to make to the Sandbox.

**Comment by jitendrasahu007** [comment]
@kpshek  thanks...
